#!/bin/sh

#### AUTOSTART ####

sxhkd &
feh --bg-fill /usr/share/backgrounds/city_sunset.jpg &
picom --experimental-backends &
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output eDP-1-1 --mode 1920x1080 --rotate normal --right-of HDMI-0 &
#google-drive-ocamlfuse /home/pascal/googledrive &
#keepass2 &

#### MONITORS ####
bspc monitor HDMI-0 -d I II III IV
bspc monitor eDP-1-1 -d V VI VII VIII IX X

#### CONFIG ####
bspc config border_width         1
bspc config window_gap           4 
bspc config top_padding		20
bspc config bottom_padding 	 0
bspc config left_padding	 0
pspc config right_padding 	 0

bspc config remove_disabled_monitors true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### BSPWM COLORING ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e" #1e1e1e
bspc config focused_border_color "#ff0000" #5e81ac
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

#### DEFAULT RULES ####
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### OWN RULES ####
bspc rule -a Zathura state=tiled

rclone mount arch_googledrive: /media/google_drive/ &
#### PANELS ####

